apiVersion: v1
kind: Service
metadata:
  name: {{ include "zyte-test-websites.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "zyte-test-websites.labels" . | indent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    {{- include "zyte-test-websites.selectorLabels" . | indent 4 }}
