version: 2.1

workflows:
  publish:
    jobs:
      - build_image:
          name: Build Image
          context:
            - Docker

jobs:
  build_image:
    machine:
      image: ubuntu-2404:2024.05.1
      docker_layer_caching: true
    environment:
      APPNAME: zyte-test-websites
    steps:
      - checkout
      - run:
          name: Build docker image
          command: |
            export APPIMAGE=images.scrapinghub.com/${APPNAME}/${CIRCLE_BRANCH}:${CIRCLE_SHA1:0:7}
            docker build -t $APPIMAGE .
      - run:
          name: Push docker image
          command: |
            export APPIMAGE=images.scrapinghub.com/${APPNAME}/${CIRCLE_BRANCH}
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin $DOCKER_REGISTRY
            docker tag $APPIMAGE:${CIRCLE_SHA1:0:7} $APPIMAGE:latest
            docker push $APPIMAGE