{{- $root := . -}}
{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "zyte-test-websites.name" . }}
  labels:
    {{- include "zyte-test-websites.labels" . | indent 4 }}
  {{- range $key, $value := .Values.ingress.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ include "zyte-test-websites.hostname" . }}
      http:
        paths:
          - path: {{ .Values.ingress.path | default "/" | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "zyte-test-websites.name" . }}
                port:
                  number: 80
  {{- range .Values.ingress.additionalHostnames }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.ingress.path | default "/" | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "zyte-test-websites.name" $root }}
                port:
                  number: 80
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ include "zyte-test-websites.hostname" . }}
        {{- range .Values.ingress.additionalHostnames }}
        - {{ . }}
        {{- end }}
      {{- if .Values.ingress.secretName }}
      secretName: {{ .Values.ingress.secretName }}
      {{- end }}
  {{- end -}}
{{- end -}}
